﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Collections.ObjectModel;
using System.Reactive;
using System.Threading.Tasks;
using Gitter.Model;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Gitter.Services.Abstract
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIGitterApi : IGitterApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIGitterApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<ObservableCollection<Room>> GetRooms(string accessToken)
        {
            var arguments = new object[] { accessToken };
            return (Task<ObservableCollection<Room>>) methodImpls["GetRooms"](Client, arguments);
        }

        public virtual Task<ObservableCollection<Message>> GetMessages(string roomId,string accessToken)
        {
            var arguments = new object[] { roomId,accessToken };
            return (Task<ObservableCollection<Message>>) methodImpls["GetMessages"](Client, arguments);
        }

        public virtual Task<ObservableCollection<User>> GetRoomUsers(string roomId,string accessToken)
        {
            var arguments = new object[] { roomId,accessToken };
            return (Task<ObservableCollection<User>>) methodImpls["GetRoomUsers"](Client, arguments);
        }

        public virtual Task<Unit> SendMessage(string roomId,SendMessage message,string accessToken)
        {
            var arguments = new object[] { roomId,message,accessToken };
            return (Task<Unit>) methodImpls["SendMessage"](Client, arguments);
        }

        public virtual Task<Unit> UpdateMessage(string roomId,string chatMessageId,string text,string accessToken)
        {
            var arguments = new object[] { roomId,chatMessageId,text,accessToken };
            return (Task<Unit>) methodImpls["UpdateMessage"](Client, arguments);
        }

    }
}


